### PR TITLE
Fix minor version

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Hi html5-php Maintainers

I fixed minor version in installation section for adding as dependency in composer.json

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Useless repo, 1 month over
Did you ever reply, or at least close this pr.

**Comment by mundschenk-at** [comment]
I'm not the maintainer, but you gave no reason why that change would be beneficial. What does changing the minor version actually accomplish? It will install the same library version due to the `^` operator.

**Comment by PuneetGopinath** [comment]
No, it will install 2.7.x instead of 2.0.x
And x is the latest patch version of the minor version

**Comment by PuneetGopinath** [comment]
See https://getcomposer.org/doc/articles/versions.md#caret-version-range-
> treats ^0.3 as >=0.3.0 <0.4.0
It means that it treats `^2.0` as `>=2.0.0 <2.1.0`

**Comment by mundschenk-at** [comment]
> See https://getcomposer.org/doc/articles/versions.md#caret-version-range-
> 
> > treats ^0.3 as >=0.3.0 <0.4.0
> 
> It means that it treats `^2.0` as `>=2.0.0 <2.1.0`

That's a misleading partial quote, as the sentence starts with _"For pre-1.0 versions it also acts with safety in mind and"_.

**Comment by PuneetGopinath** [comment]
Ohh, ok

**Comment by mundschenk-at** [comment]
> No, it will install 2.7.x instead of 2.0.x
> And x is the latest patch version of the minor version

This is not true. It will install the latest release of the same semver major version number.

**Comment by PuneetGopinath** [comment]
Anyway, if I am wrong
Please mention that I am wrong
All kept quiet for a month, then how will I trust you?

**Comment by mundschenk-at** [comment]
I don't know why you will or will not trust "us" (as I said, I'm not a maintainer), but if you propose a PR, you should argue why it is necessary and beneficial. 

We are all in the middle for a pandemic, so a PR without a preexisting issue and no compelling reasoning will probably not get much brain bandwidth?

**Pull request closed without merging**
