### PR TITLE
[WIP] Improve coding style in various places

### PR DESCRIPTION
**Pull request by tgalopin**

### CODE REVIEW

**Comment by goetas** [comment]
What about introducing some official coding standard and verify it on Travis ci? Something as doctrine Cs 5, Csfixer or similar.

You are doing a great job in cleaning up the codebase, but without some automated ci, sooner or later will become messy again

**Comment by tgalopin** [comment]
I would be absolutely up for that :) . I didn't want to introduce it out of the blue, I know some people are not really fond of these tools. What do you think of StyleCI or PrettyCI? They are much quicker to setup and free for OSS projects.

**Comment by mundschenk-at** [comment]
I can provide help with integrating `phpcs` into the Travis or Scrutinizer workflow. The main issue would seem to be deciding on a coding style?

**Comment by tgalopin** [comment]
I suggest we base our coding style on a known set like Symfony or Doctrine one (I tend to much prefer the Symfony one personally). WYDT?

**Comment by goetas** [comment]
>  What do you think of StyleCI or PrettyCI? They are much quicker to setup and free for OSS projects.

I wanted something that can be run locally before pushing. Both  StyleCI or PrettyCI are fancy, but running them locally is not tat obvious.

@mundschenk-at `phpcs` would be great. [here](https://github.com/willdurand/Hateoas/pull/271/files) you can find an integration of PHPCS I did in the past and I think could be a good starting point.

**Comment by tgalopin** [comment]
@mundschenk-at do you want to do it or should I do it in this PR :) ?

**Comment by tgalopin** [comment]
I had a bit of time, I started to work here in the end.

**Comment by mundschenk-at** [comment]
Minimum PHP version should not increase.

**Comment by tgalopin** [comment]
Yes, I'm working on it ;) .

**Comment by tgalopin** [comment]
Well actually I think it's okay, as we are in require-dev, we can decide the run the PHP-CS check only in 7.1 for instance. I'll do that tomorrow :) .

**Comment by mundschenk-at** [comment]
No, I didn't mean the style check itself. You are changing library source files to PHP 7.1 syntax (probably due to automatic fixing).

**Comment by stof** [comment]
using the doctrine coding standards is a bad choice given that the min version is PHP 5.3. The Doctrine coding standards are precisely opinionated in favor of using PHP 7.1+ features (as that's the min PHP version of Doctrine now)

**Pull request closed without merging**
