### PR TITLE
Set default encoding in the DOMDocument object

### PR DESCRIPTION
**Pull request by idimopoulos**
Solves https://github.com/Masterminds/html5-php/issues/167 (If I am correct).

### CODE REVIEW

**Comment by goetas** [comment]
Hi, thanks for the PR. Is there a way to test this?

**Comment by idimopoulos** [comment]
@goetas I am working on it right now. There is a very easy to test this in `\Masterminds\HTML5\Tests\Parser\DOMTreeBuilderTest::testDocument` by simply checking if the resulting `$doc` object has the correct encoding.

What I am worrying about though, is whether the encoding should derive by the document itself i.e. the `charset` attribute in the `head` HTML element tag. I will be back shortly with something.

**Comment by idimopoulos** [comment]
I forced pushed to add a failing test first and then I will push the fix.
The thing is that I am not entirely sure about the nature of the parser. 
In `\Masterminds\HTML5::parse` the scanner is instantiated with the options `!empty($options['encoding']) ? $options['encoding'] : 'UTF-8'`

However, this means only that the scanner is meant to scan using a 'UTF-8' parser (I mean that it will deal with the document considering that it is a UTF-8 document even if it is not.
However, the `DOMTreeBuilder`, that actually has the `$doc` property, should have the encoding of the document/input itself. Since it is an HTML5 parser, I can assume that an HTML is expected to be passed. However, the input is not required to build the `DOMTreeBuilder`.

I see all over around that the UTF-8 is used as the default option but I am not sure whether that should apply for the `DOMTreeBuilder` (maybe you people can shed some light here).
In any way, I am providing the fix as in our case, as I mentioned in https://github.com/Masterminds/html5-php/issues/167, Symfony uses the `new \DOMDocument('1.0', $charset);` which is passed in the method to build the Document so even for the legacy cases, the charset is not detected through the head metatag. Thus, at least to be consistent to begin with, we could have this set to UTF-8 by default.

Do you think I need to open an issue to automatically detect the charset from the HTML if available?

**Comment by idimopoulos** [comment]
Sorry I messed up a bit with the commit messages.

**Comment by goetas** [comment]
Looks good, thanks!

**Pull request merged**
