### PR TITLE
Enable composer cache

### PR DESCRIPTION
**Pull request by goetas**

### CODE REVIEW

**Comment by goetas** [comment]
no big differences... maybe 10-15 % of improvements.

Is it worth?

**Comment by mattfarina** [comment]
So, I'll get a little technical here because this is interesting.

This is really a shift from crabbing checkouts of projects as a tarball and transferring it between GitHub and Travis CI to a setup where package versions as tarballs are stored locally in Travis (moved around as needed) and only new versions are fetched. The fact they are close in performance is a testament to the performance tuning done by GitHub.

Because GitHub has to regularly checkout a version and perform computation to create the tarballs I'm inclined to use the caching. I suspect caching is, on a combined system scale, lower on computation.

Anyone else have thoughts?

**Comment by mattfarina** [comment]
Also, this should be cherry picked to the 2.x branch once merged.

**Comment by goetas** [comment]
So you look "pro" to this feature, right?

**Comment by mattfarina** [comment]
@goetas Yeah, I'm pro-cache in this case. We can always undo this later pretty easily.

**Comment by goetas** [comment]
:+1:

**Pull request merged**
