### PR TITLE
Allow to pass a charset to the Scanner

### PR DESCRIPTION
**Pull request by tgalopin**
Also fixes a few comments indentation.

### CODE REVIEW

**Comment by goetas** [comment]
Hi, instead of adding a new parameter, why not add an option to the option array?
It will be consistent with the rest of the public api

**Comment by tgalopin** [comment]
Okay, no problem :) .

**Comment by tgalopin** [comment]
Sorry, working on it, the SymfonyCon Lisbon was tiring :) .

**Comment by tgalopin** [comment]
I didn't change this, I just expanded the conditionnals using only ifs instead of elseifs :) .

**Comment by goetas** [comment]
Right! I should stop making code reviews using the phone! :smile:

**Comment by goetas** [comment]
Can you add some tests for this feature?

**Comment by tgalopin** [comment]
I added tests :) .

**Comment by goetas** [comment]
hmm, it looks something did not work

**Comment by tgalopin** [comment]
I updated the tests :) .

**Comment by tgalopin** [comment]
Done \o/

**Comment by tgalopin** [comment]
I think this is ready for review :)!

**Comment by goetas** [comment]
Thanks!

**Comment by goetas** [comment]
Do you need a tag for it or can wait?

**Comment by tgalopin** [comment]
A tag would be nice, but it can wait a few days/weeks if needed :) .

**Comment by goetas** [comment]
released as [2.6.0](https://github.com/Masterminds/html5-php/releases/tag/2.6.0)

**Pull request merged**
