### PR TITLE
Added compatibility class for 2.x version

### PR DESCRIPTION
**Pull request by goetas**
fixes https://github.com/Masterminds/html5-php/issues/101

### CODE REVIEW

**Comment by goetas** [comment]
renamed the main class and added two classes that inherits from the first one

**Comment by goetas** [comment]
ping @mattfarina @technosophos

**Comment by mattfarina** [comment]
@goetas I just returned from vacation. I'll look at this and some other things this week.

**Comment by stof** [comment]
do we need to have an abstract class ? We could have the compat class extending the normal one directly.

**Comment by tgalopin** [comment]
I think Symfony's way is great in terms of semantic versionning: in Symfony, we bump the major only when we want to break compatiblity, and we don't add any new feature in it. For instance, 3.4 and 4.0 are strictly the same in terms of features, but 4.0 is 3.4 with all compatibility layers removed.

We could do this in this library as well. If you think that's a good idea, I propose the following:

- we backport features from master to 2.x (including https://github.com/Masterminds/html5-php/pull/97)
- we remove the current master branch and rename 2.x to master
- all new features and bug fixes are added to master
- when we need to break BC (for PHP version support for instance), we create a new 2.x branch based on the master of the time, we introduce the BC break into master and we release master as 3.x

With this, we would be able to work on 2.x as long as we wish, and when we think a new major is useful, we create a new master, release it as 3.x and work only on bug fixes in 2.x. Moreover, because of this organization, we would be able to "easily" port 2.x bug fixes into 3.x using by merging 2.x into master.

WDYT?

**Comment by stof** [comment]
AFAICT the main differences between 2.x and master currently are:

- renaming the class/namespace
- removing the return value for `Scanner::next`

So it might not deserve a major version yet (unless you are strong about the class renaming, which is an annoying BC break anyway)



>     * when we need to break BC (for PHP version support for instance)

Bumping the min PHP version is not even necessarily a BC break (assuming that your composer.json is properly configured), as composer will take that into account (otherwise, any other change to dependencies would also have to be considered one). I would say that dropping support for dead PHP versions in a minor version is perfectly fine (this needs to be evaluated based on the needs of the target audience vs the cost of supporting them).

**Comment by tgalopin** [comment]
I totally agree that a major does not seems needed for now :) .

**Comment by goetas** [comment]
as soon as I will have some time, will follow @tgalopin suggestion in https://github.com/Masterminds/html5-php/pull/103#issuecomment-437001558 and move back 2.x to the master branch

**Comment by goetas** [comment]
Decided to stop working on 3.0 (the one set almost 2 years ago) and put more efforts on 2.x.

**Pull request closed without merging**
