### PR TITLE
Change the main class name to Html5 instead of HTML5

### PR DESCRIPTION
**Pull request by goetas**
This PR renames the main HTML5 class and increments the HTML5-PHP version to `3.0-dev`

Closes https://github.com/Masterminds/html5-php/issues/79

### CODE REVIEW

**Comment by goetas** [comment]
I've just changed the class name... do we have to change also the namespace `Masterminds\HTML5` to  `Masterminds\Html5` ?

**Comment by hakre** [comment]
@goetas Namespaces are just part of the fully qualified class name (FQCN), so the rule is for these, too.

I would also do that to keep this aligned with each other. Only changing the one class w/o the namespace looks funny.

**Comment by mattfarina** [comment]
The directory name for `HTML5` should become `Html5`. I can imagine case sensitivity issues coming up.

**Comment by goetas** [comment]
It is not required, but, may we drop php 5.3 support?

**Comment by mattfarina** [comment]
Kinda crazy that [5.3 is the most popular version of PHP](http://w3techs.com/technologies/details/pl-php/5/all). Yet, it's no longer a supported version. Despite that, it's likely ok to drop 5.3 support. @technosophos any thoughts?

**Comment by technosophos** [comment]
I'm fine dropping PHP 5.3 support.

**Comment by hakre** [comment]
I don't see what requires the drop. of 5.3 support. Just wondering.

**Comment by goetas** [comment]
To be honest there is no a real case for dropping php 5.3, it was just a thought...

**Comment by PhenX** [comment]
I think the more versions of php you the support, the better it is for the
community. Especially if a more recent version is not a necessity.

**Comment by goetas** [comment]
:+1:

**Comment by mattfarina** [comment]
What would you want to change that drops 5.3 support?

**Comment by goetas** [comment]
Exactly nothing... it was just to encourage people to update their php envs...

**Comment by hakre** [comment]
That normally works best with talking to them and to show them that there is actually use in upgrading (not just breaking if not upgrading). But I can feel with you. Sometime I wish I could slap someone in the face to not upgrade. For upgrading consider PHP 5.6 please.

**Comment by mattfarina** [comment]
Something to consider is the number of people on shared hosting. The long tail of PHP environments is what has made PHP successful. Sometimes you can't control the version of PHP you are on.

**Comment by goetas** [comment]
ok, then lets stay with php 5.3! :-)

**Comment by mattfarina** [comment]
If you've not seen it already... PHP versions in the wild... http://w3techs.com/technologies/details/pl-php/5/all

**Comment by technosophos** [comment]
That's depressing.

**Comment by goetas** [comment]
@mattfarina I've posted this week the same link to some colleges :smile:

**Comment by mattfarina** [comment]
It appears the class names were all hit and all the tests pass. Is there anything else to do before we branch the 2.x work (for future bugfix releases) and merge this breaking change? I'm happy to do it.

**Comment by goetas** [comment]
Then ok, I the next days I will prepare the `2.1.3` release, create a `2.x` branch and then merge this PR into `master`

**Comment by mattfarina** [comment]
@goetas yay. let me know if there's anything you need done. I have some time again for these kinds of things.

**Comment by goetas** [comment]
Rebased again. Since we are going to prepare the release 3.0. Do we need to prepare some document? I mean html pages, readme entries....?

**Comment by mattfarina** [comment]
@goetas How about we use this to get the 3.x working going. Once the 2.x branch is in place for bug-fixes and this is merged to master we can prep for a release. we don't need to do one right away.

I'm considering poking at #80 and #86 before we release a 3.0

**Comment by goetas** [comment]
@mattfarina  :+1: 

I've created the 2.x branch and set is as default branch. In the tomorrow i will merge this PR into master.

When the 3.0 branch will be ready we can set again the master branch as default branch. I will prefer to wait a bit for releasing 3.0 to avoid having a 4.0 version in few weeks/months.

Regarding: 
* #80 I'm not sure if we have to do something or not. With xdebug disabled, results are much better (plus if you are considering to implement #86, things and preformance will change a lot).
* #86 i think that can land in 3.0, but since I'm not too much into the topic, I'm not the right person to do implement :)

**Comment by mattfarina** [comment]
@goetas I can handle #86 if someone else isn't going to try. I'd like to look over #80 but I don't know if there is something to do. Either way it would be good to have a response.

I'll poke at those after you merge this in.

**Comment by mattfarina** [comment]
@goetas FYI, if you would like I'm happy to handle the merge and all that goes along with it. Just let me know. I have the time now and am happy to help.

**Pull request merged**
